# Generated by Django 3.2.7 on 2022-11-24 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
    ]
